name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-lint-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO: add macos-latest after figuring out why tests timeout in GH CI
        os: [ubuntu-latest, windows-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # Comment out cache line when testing with act:
          # (Test command is: act --platform ubuntu-latest=lucasalt/act_base:latest)
          cache: 'npm'
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npx prettier . --check
      - run: npm run lint
      - run: npm test
