name: CI

on:
  push:
    branches:
      - main
  pull_request:


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-individual:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 16 ]
        project:
          [
            activities-examples,
            mutex,
            nestjs-exchange-rates,
            timer-examples
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # Comment out cache line when testing with act:
          # (Test command is: act --platform ubuntu-latest=lucasalt/act_base:latest)
          cache: 'npm'
      - run: yarn
        working-directory: ${{ matrix.project }}
      - run: npm run build
        working-directory: ${{ matrix.project }}
      - run: npm test
        working-directory: ${{ matrix.project }}

  lint-individual:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          [
            activities-cancellation-heartbeating,
            activities-dependency-injection,
            activities-examples,
            activities-sticky-queues,
            child-workflows,
            continue-as-new,
            cron-workflows,
            dsl-interpreter,
            ejson,
            encryption,
            expense,
            fetch-esm,
            food-delivery,
            grpc-calls,
            hello-world,
            hello-world-js,
            hello-world-mtls,
            instrumentation,
            interceptors-opentelemetry,
            logger-shared,
            monorepo-folders,
            mutex,
            nestjs-exchange-rates,
            nextjs-ecommerce-oneclick,
            patching-api,
            production,
            protobufs,
            query-subscriptions,
            replay-history,
            saga,
            schedules,
            search-attributes,
            signals-queries,
            sinks,
            snippets,
            state,
            timer-examples,
            timer-progress
          ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          # Comment out cache line when testing with act:
          # (Test command is: act --platform ubuntu-latest=lucasalt/act_base:latest)
          cache: 'npm'
      - run: yarn
        working-directory: ${{ matrix.project }}
      - run: npm run build
        working-directory: ${{ matrix.project }}
        if: ${{ matrix.project != 'hello-world-js' }}
      - run: npm run lint
        working-directory: ${{ matrix.project }}
      - run: npx prettier . --check
        working-directory: ${{ matrix.project }}
 