name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-lint-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # add windows-latest when supported by SDK
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          # Comment out cache line when testing with act:
          # (Test command is: act --platform ubuntu-latest=lucasalt/act_base:latest)
          cache: 'npm'
      - run: npm ci
      - run: npx lerna bootstrap --no-ci --npm-client=yarn
      - run: npm run build
      - run: npx prettier . --check
      - run: npm run lint
      - name: Get Temporal docker-compose.yml
        run: wget https://raw.githubusercontent.com/temporalio/docker-compose/main/docker-compose.yml
        # TODO: Test on MacOS once we get docker-compose running on the GH actions Mac instance
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Start Temporal Server
        run: docker-compose up -d
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Install sample deps
        run: npm install
        working-directory: activities-examples
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - name: Wait for Temporal Server
        run: node .scripts/wait-on-temporal.mjs
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - run: npm test
        working-directory: activities-examples
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
